run:
  timeout: 20m
  issue-exit-code: 0 # we will change this later
  tests: true
  skip-dirs-use-default: true
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  exclude-rules:
    - path: /
      text: "parameter 'ctx' seems to be unused"
      linters:
        - revive
    - path: /
      text: "parameter 'req' seems to be unused"
      linters:
        - revive
    - path: /
      text: "parameter 'context' seems to be unused"
      linters:
        - revive
    - path: /
      text: "parameter 'request' seems to be unused"
      linters:
        - revive
        
output:
  print-linter-name: true
  sort-results: true
  uniq-by-line: false
  print-issued-lines: true

linters:
  disable-all: true
  fast: false
  enable:
    # A stricter replacement for gofmt.
    - gofumpt
    # Inspects source code for security problems.
    - gosec
    # Check for correctness of programs.
    - govet
    # Drop-in replacement of golint.
    - revive
