// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	collectors "github.com/dell/csi-powerstore/v2/pkg/collectors"

	gopowerstore "github.com/dell/gopowerstore"

	mock "github.com/stretchr/testify/mock"
)

// ApplianceClient is an autogenerated mock type for the ApplianceClient type
type ApplianceClient struct {
	mock.Mock
}

// GetAppliances provides a mock function with given fields: ctx
func (_m *ApplianceClient) GetAppliances(ctx context.Context) ([]gopowerstore.ApplianceInstance, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAppliances")
	}

	var r0 []gopowerstore.ApplianceInstance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]gopowerstore.ApplianceInstance, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []gopowerstore.ApplianceInstance); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gopowerstore.ApplianceInstance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCluster provides a mock function with given fields: ctx
func (_m *ApplianceClient) GetCluster(ctx context.Context) (collectors.ClusterInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCluster")
	}

	var r0 collectors.ClusterInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (collectors.ClusterInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) collectors.ClusterInfo); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(collectors.ClusterInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SpaceMetricsByAppliance provides a mock function with given fields: ctx, applianceID, interval
func (_m *ApplianceClient) SpaceMetricsByAppliance(ctx context.Context, applianceID string, interval gopowerstore.MetricsIntervalEnum) ([]gopowerstore.SpaceMetricsByApplianceResponse, error) {
	ret := _m.Called(ctx, applianceID, interval)

	if len(ret) == 0 {
		panic("no return value specified for SpaceMetricsByAppliance")
	}

	var r0 []gopowerstore.SpaceMetricsByApplianceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, gopowerstore.MetricsIntervalEnum) ([]gopowerstore.SpaceMetricsByApplianceResponse, error)); ok {
		return rf(ctx, applianceID, interval)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, gopowerstore.MetricsIntervalEnum) []gopowerstore.SpaceMetricsByApplianceResponse); ok {
		r0 = rf(ctx, applianceID, interval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gopowerstore.SpaceMetricsByApplianceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, gopowerstore.MetricsIntervalEnum) error); ok {
		r1 = rf(ctx, applianceID, interval)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SpaceMetricsByCluster provides a mock function with given fields: ctx, clusterID, interval
func (_m *ApplianceClient) SpaceMetricsByCluster(ctx context.Context, clusterID string, interval gopowerstore.MetricsIntervalEnum) ([]gopowerstore.SpaceMetricsByClusterResponse, error) {
	ret := _m.Called(ctx, clusterID, interval)

	if len(ret) == 0 {
		panic("no return value specified for SpaceMetricsByCluster")
	}

	var r0 []gopowerstore.SpaceMetricsByClusterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, gopowerstore.MetricsIntervalEnum) ([]gopowerstore.SpaceMetricsByClusterResponse, error)); ok {
		return rf(ctx, clusterID, interval)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, gopowerstore.MetricsIntervalEnum) []gopowerstore.SpaceMetricsByClusterResponse); ok {
		r0 = rf(ctx, clusterID, interval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gopowerstore.SpaceMetricsByClusterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, gopowerstore.MetricsIntervalEnum) error); ok {
		r1 = rf(ctx, clusterID, interval)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewApplianceClient creates a new instance of ApplianceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApplianceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApplianceClient {
	mock := &ApplianceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
