// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GeneralSnapshot is an autogenerated mock type for the GeneralSnapshot type
type GeneralSnapshot struct {
	mock.Mock
}

// GetID provides a mock function with given fields:
func (_m *GeneralSnapshot) GetID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetSize provides a mock function with given fields:
func (_m *GeneralSnapshot) GetSize() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GetSourceID provides a mock function with given fields:
func (_m *GeneralSnapshot) GetSourceID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
