/*
 *
 * Copyright © 2021-2023 Dell Inc. or its subsidiaries. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	controller "github.com/dell/csi-powerstore/v2/pkg/controller"
	mock "github.com/stretchr/testify/mock"
)

// GeneralSnapshot is an autogenerated mock type for the GeneralSnapshot type
type GeneralSnapshot struct {
	mock.Mock
}

// GetID provides a mock function with given fields:
func (_m *GeneralSnapshot) GetID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetSize provides a mock function with given fields:
func (_m *GeneralSnapshot) GetSize() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GetSourceID provides a mock function with given fields:
func (_m *GeneralSnapshot) GetSourceID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetType provides a mock function with given fields:
func (_m *GeneralSnapshot) GetType() controller.SnapshotType {
	ret := _m.Called()

	var r0 controller.SnapshotType
	if rf, ok := ret.Get(0).(func() controller.SnapshotType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(controller.SnapshotType)
	}

	return r0
}
