// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NFSv4ACLsInterface is an autogenerated mock type for the NFSv4ACLsInterface type
type NFSv4ACLsInterface struct {
	mock.Mock
}

// SetNfsv4Acls provides a mock function with given fields: acls, dir
func (_m *NFSv4ACLsInterface) SetNfsv4Acls(acls string, dir string) error {
	ret := _m.Called(acls, dir)

	if len(ret) == 0 {
		panic("no return value specified for SetNfsv4Acls")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(acls, dir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNFSv4ACLsInterface creates a new instance of NFSv4ACLsInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNFSv4ACLsInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *NFSv4ACLsInterface {
	mock := &NFSv4ACLsInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
