// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	csi "github.com/container-storage-interface/spec/lib/go/csi"
	fs "github.com/dell/csi-powerstore/pkg/common/fs"

	logrus "github.com/sirupsen/logrus"

	mock "github.com/stretchr/testify/mock"
)

// NodeVolumePublisher is an autogenerated mock type for the NodeVolumePublisher type
type NodeVolumePublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, logFields, _a2, cap, isRO, targetPath, stagingPath
func (_m *NodeVolumePublisher) Publish(ctx context.Context, logFields logrus.Fields, _a2 fs.FsInterface, cap *csi.VolumeCapability, isRO bool, targetPath string, stagingPath string) (*csi.NodePublishVolumeResponse, error) {
	ret := _m.Called(ctx, logFields, _a2, cap, isRO, targetPath, stagingPath)

	var r0 *csi.NodePublishVolumeResponse
	if rf, ok := ret.Get(0).(func(context.Context, logrus.Fields, fs.FsInterface, *csi.VolumeCapability, bool, string, string) *csi.NodePublishVolumeResponse); ok {
		r0 = rf(ctx, logFields, _a2, cap, isRO, targetPath, stagingPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*csi.NodePublishVolumeResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, logrus.Fields, fs.FsInterface, *csi.VolumeCapability, bool, string, string) error); ok {
		r1 = rf(ctx, logFields, _a2, cap, isRO, targetPath, stagingPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
