/*
 *
 * Copyright © 2021-2023 Dell Inc. or its subsidiaries. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	fs "github.com/dell/csi-powerstore/v2/pkg/identifiers/fs"
	"github.com/dell/csmlog"
	csi "github.com/container-storage-interface/spec/lib/go/csi"

	mock "github.com/stretchr/testify/mock"
)

// NodeVolumeStager is an autogenerated mock type for the NodeVolumeStager type
type NodeVolumeStager struct {
	mock.Mock
}

// Stage provides a mock function with given fields: ctx, req, logFields, _a3, id
func (_m *NodeVolumeStager) Stage(ctx context.Context, req *csi.NodeStageVolumeRequest, logFields csmlog.Fields, _a3 fs.Interface, id string) (*csi.NodeStageVolumeResponse, error) {
	ret := _m.Called(ctx, req, logFields, _a3, id)

	var r0 *csi.NodeStageVolumeResponse
	if rf, ok := ret.Get(0).(func(context.Context, *csi.NodeStageVolumeRequest, csmlog.Fields, fs.Interface, string) *csi.NodeStageVolumeResponse); ok {
		r0 = rf(ctx, req, logFields, _a3, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*csi.NodeStageVolumeResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *csi.NodeStageVolumeRequest, csmlog.Fields, fs.Interface, string) error); ok {
		r1 = rf(ctx, req, logFields, _a3, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
