// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	config "github.com/uber/jaeger-client-go/config"
)

// TracerConfigurator is an autogenerated mock type for the TracerConfigurator type
type TracerConfigurator struct {
	mock.Mock
}

// FromEnv provides a mock function with given fields:
func (_m *TracerConfigurator) FromEnv() (*config.Configuration, error) {
	ret := _m.Called()

	var r0 *config.Configuration
	if rf, ok := ret.Get(0).(func() *config.Configuration); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Configuration)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
