// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gopowerstore "github.com/dell/gopowerstore"
	mock "github.com/stretchr/testify/mock"
)

// VolumeClient is an autogenerated mock type for the VolumeClient type
type VolumeClient struct {
	mock.Mock
}

// GetHost provides a mock function with given fields: ctx, hostID
func (_m *VolumeClient) GetHost(ctx context.Context, hostID string) (gopowerstore.Host, error) {
	ret := _m.Called(ctx, hostID)

	if len(ret) == 0 {
		panic("no return value specified for GetHost")
	}

	var r0 gopowerstore.Host
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (gopowerstore.Host, error)); ok {
		return rf(ctx, hostID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) gopowerstore.Host); ok {
		r0 = rf(ctx, hostID)
	} else {
		r0 = ret.Get(0).(gopowerstore.Host)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hostID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHostVolumeMappingByVolumeID provides a mock function with given fields: ctx, volumeID
func (_m *VolumeClient) GetHostVolumeMappingByVolumeID(ctx context.Context, volumeID string) ([]gopowerstore.HostVolumeMapping, error) {
	ret := _m.Called(ctx, volumeID)

	if len(ret) == 0 {
		panic("no return value specified for GetHostVolumeMappingByVolumeID")
	}

	var r0 []gopowerstore.HostVolumeMapping
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]gopowerstore.HostVolumeMapping, error)); ok {
		return rf(ctx, volumeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []gopowerstore.HostVolumeMapping); ok {
		r0 = rf(ctx, volumeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gopowerstore.HostVolumeMapping)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, volumeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNFSExportByFileSystemID provides a mock function with given fields: ctx, fsID
func (_m *VolumeClient) GetNFSExportByFileSystemID(ctx context.Context, fsID string) (gopowerstore.NFSExport, error) {
	ret := _m.Called(ctx, fsID)

	if len(ret) == 0 {
		panic("no return value specified for GetNFSExportByFileSystemID")
	}

	var r0 gopowerstore.NFSExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (gopowerstore.NFSExport, error)); ok {
		return rf(ctx, fsID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) gopowerstore.NFSExport); ok {
		r0 = rf(ctx, fsID)
	} else {
		r0 = ret.Get(0).(gopowerstore.NFSExport)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fsID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNFSExports provides a mock function with given fields: ctx
func (_m *VolumeClient) GetNFSExports(ctx context.Context) ([]gopowerstore.NFSExport, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetNFSExports")
	}

	var r0 []gopowerstore.NFSExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]gopowerstore.NFSExport, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []gopowerstore.NFSExport); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gopowerstore.NFSExport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNFSExportsByFileSystemID provides a mock function with given fields: ctx, fsID
func (_m *VolumeClient) GetNFSExportsByFileSystemID(ctx context.Context, fsID string) ([]gopowerstore.NFSExport, error) {
	ret := _m.Called(ctx, fsID)

	if len(ret) == 0 {
		panic("no return value specified for GetNFSExportsByFileSystemID")
	}

	var r0 []gopowerstore.NFSExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]gopowerstore.NFSExport, error)); ok {
		return rf(ctx, fsID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []gopowerstore.NFSExport); ok {
		r0 = rf(ctx, fsID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gopowerstore.NFSExport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fsID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVolumes provides a mock function with given fields: ctx
func (_m *VolumeClient) GetVolumes(ctx context.Context) ([]gopowerstore.Volume, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetVolumes")
	}

	var r0 []gopowerstore.Volume
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]gopowerstore.Volume, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []gopowerstore.Volume); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gopowerstore.Volume)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListFS provides a mock function with given fields: ctx
func (_m *VolumeClient) ListFS(ctx context.Context) ([]gopowerstore.FileSystem, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListFS")
	}

	var r0 []gopowerstore.FileSystem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]gopowerstore.FileSystem, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []gopowerstore.FileSystem); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gopowerstore.FileSystem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVolumeClient creates a new instance of VolumeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVolumeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *VolumeClient {
	mock := &VolumeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
