// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	csi "github.com/container-storage-interface/spec/lib/go/csi"

	gopowerstore "github.com/dell/gopowerstore"

	mock "github.com/stretchr/testify/mock"
)

// VolumePublisher is an autogenerated mock type for the VolumePublisher type
type VolumePublisher struct {
	mock.Mock
}

// CheckIfVolumeExists provides a mock function with given fields: ctx, client, volID
func (_m *VolumePublisher) CheckIfVolumeExists(ctx context.Context, client gopowerstore.Client, volID string) error {
	ret := _m.Called(ctx, client, volID)

	if len(ret) == 0 {
		panic("no return value specified for CheckIfVolumeExists")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, gopowerstore.Client, string) error); ok {
		r0 = rf(ctx, client, volID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publish provides a mock function with given fields: ctx, publishContext, req, client, kubeNodeID, volumeID, isRemote
func (_m *VolumePublisher) Publish(ctx context.Context, publishContext map[string]string, req *csi.ControllerPublishVolumeRequest, client gopowerstore.Client, kubeNodeID string, volumeID string, isRemote bool) (*csi.ControllerPublishVolumeResponse, error) {
	ret := _m.Called(ctx, publishContext, req, client, kubeNodeID, volumeID, isRemote)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 *csi.ControllerPublishVolumeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, *csi.ControllerPublishVolumeRequest, gopowerstore.Client, string, string, bool) (*csi.ControllerPublishVolumeResponse, error)); ok {
		return rf(ctx, publishContext, req, client, kubeNodeID, volumeID, isRemote)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, *csi.ControllerPublishVolumeRequest, gopowerstore.Client, string, string, bool) *csi.ControllerPublishVolumeResponse); ok {
		r0 = rf(ctx, publishContext, req, client, kubeNodeID, volumeID, isRemote)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*csi.ControllerPublishVolumeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string, *csi.ControllerPublishVolumeRequest, gopowerstore.Client, string, string, bool) error); ok {
		r1 = rf(ctx, publishContext, req, client, kubeNodeID, volumeID, isRemote)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVolumePublisher creates a new instance of VolumePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVolumePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *VolumePublisher {
	mock := &VolumePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
